// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DirectUploadController from "./direct_upload_controller"
application.register("direct-upload", DirectUploadController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import QuestionFormController from "./question_form_controller"
application.register("question-form", QuestionFormController)

import QuizFormController from "./quiz_form_controller"
application.register("quiz-form", QuizFormController)

import SlimSelectController from "./slim_select_controller"
application.register("slim-select", SlimSelectController)
